name: OSV-Scanner

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]
  schedule:
    - cron: '40 11 * * 4'
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  scan:
    name: OSV-Scanner
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run OSV-Scanner
        uses: google/osv-scanner-action/osv-scanner-action@<NEW-SHA>  # v2.3.5
        with:
          scan-args: |-
            --format=sarif
            --output=results.sarif
            --lockfile=athena/requirements.txt
        continue-on-error: true

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4.35.2
        with:
          sarif_file: results.sarif
          category: osv-scanner
